annotation_folder = "<datasets_folder_path>/communication_multiview/annotations_raw"
napari_output = "<output_folder_path>/connectors/napari_import/body_joints"

log_level = "INFO"
log_file_path = "<napari_output>/napari_import_body_joints.log"

export_csv = true

[run.sequence_xyz]
input = "<annotation_folder>/body_joints_napari"
output = "<napari_output>/sequence_xyz_body_joints.npz"
start = 0
end = -1
fps = 30  
reset_frames = false
