# This is a template file, do not add your paths here.
# Create a local copy of this file called 'machine_specific_paths.toml' and
# edit that one. The 'machine_specific_paths.toml' is added to the '.gitignore'.

# Absolute path to the directory in which all datasets are stored (str)
datasets_folder_path = ''

# Directory for saving toolbox output as an absolute path (str)
output_folder_path = ''

# Where to find your conda (miniconda or anaconda) installation as absolute path (str)
conda_path = ''          
