import json
import os

from nicetoolbox_core.audio_loaders import AudioStreamLoader
from nicetoolbox_core.data.json_schema import AudioDiarization, AudioTranscription, SpeakerAlignedTranscription

from ....configs.schemas.detectors_instances_configs import MethodDetectorRuntime
from ....utils.srt import SrtWriter
from ....utils.video import render_subtitled_track_video
from ...detector_outputs import DetectorOutput, JsonDetectorOutput
from ..base_method import BaseMethod
from .whisperx_utils import to_audio_diarization, to_audio_transcription, to_speaker_aligned_transcription

# Raw packs written by whisperx_inference.py
RAW_TRANSCRIPTION_JSON_NAME = "whisperx_transcription_raw.json"
RAW_DIARIZATION_JSON_NAME = "whisperx_diarization_raw.json"
RAW_SPEAKER_ALIGNED_JSON_NAME = "whisperx_speaker_aligned_raw.json"


class WhisperX(BaseMethod):
    algorithm_type = "whisperx"
    components = ["audio_transcription", "audio_diarization", "speaker_aligned_transcription"]

    outputs = [
        JsonDetectorOutput("audio_transcription", schema=AudioTranscription),
        JsonDetectorOutput("audio_diarization", schema=AudioDiarization),
        JsonDetectorOutput("speaker_aligned_transcription", schema=SpeakerAlignedTranscription),
    ]

    def _initialize_detector(self) -> MethodDetectorRuntime:
        if not self.data.has_audio():
            raise RuntimeError("WhisperX requires audio data but no audio was prepared.")

        # Initialize audio loader for visualization and post-processing
        self.audio_loader = AudioStreamLoader(
            config=self.data.get_input_recipes(), expected_tracks=self.detector_config.track_names
        )

        return super()._initialize_detector()

    def _load_raw(self, component: str, raw_name: str) -> dict:
        """Load a component's raw inference pack from its out_folder."""
        with open(os.path.join(self.out_folders[component], raw_name)) as f:
            return json.load(f)

    def post_inference(self) -> DetectorOutput:
        """Convert the raw inference packs into this detector's component outputs."""
        # Timestamps are relative to the subsequence, since inference is handed sliced audio.
        # Recording where it starts lets a consumer place them back on the source timeline.
        start = self.audio_loader.offset_seconds
        length = self.audio_loader.duration_seconds

        raw_transcription = self._load_raw("audio_transcription", RAW_TRANSCRIPTION_JSON_NAME)
        transcription = to_audio_transcription(
            raw_transcription,
            subsequence_start=start,
            subsequence_length=length,
            algorithm=self.algorithm_instance,
        )

        raw_diarization = self._load_raw("audio_diarization", RAW_DIARIZATION_JSON_NAME)
        diarization = to_audio_diarization(
            raw_diarization,
            subsequence_start=start,
            subsequence_length=length,
            algorithm=self.algorithm_instance,
        )

        raw_speaker_aligned = self._load_raw("speaker_aligned_transcription", RAW_SPEAKER_ALIGNED_JSON_NAME)
        speaker_aligned = to_speaker_aligned_transcription(
            raw_speaker_aligned,
            subsequence_start=start,
            subsequence_length=length,
            algorithm=self.algorithm_instance,
        )

        # SRTs feed the subtitled-video visualization. Both transcription components get one so
        # any difference introduced by speaker alignment is visible side by side.
        srt_writer = SrtWriter()
        srt_writer.write_tracks(transcription.tracks, self.out_folders["audio_transcription"])
        srt_writer.write_tracks(speaker_aligned.tracks, self.out_folders["speaker_aligned_transcription"])

        out = DetectorOutput()
        out.add_json("audio_transcription", transcription)
        out.add_json("audio_diarization", diarization)
        out.add_json("speaker_aligned_transcription", speaker_aligned)
        return out

    def visualization(self, _) -> None:
        """
        Generates visualizations overlaying SRT subtitles onto video files.

        Uses the SRT files generated by our own SrtWriter in post_inference (one per track per
        component). We render both the audio_transcription and the speaker_aligned_transcription
        components so that any differences introduced by the speaker-alignment phase are visible.

        For each track we create a new video from the video frames (if available) or a black
        background (if not) and overlay the SRT subtitles onto it.
        """
        if not self.visualize:
            return

        for component in ("audio_transcription", "speaker_aligned_transcription"):
            self._visualize_component(component)

    def _visualize_component(self, component: str) -> None:
        """Bake the per-track SRT of a single component into a subtitled video."""
        video_recipe = self.data.get_input_recipes().video_input_recipe
        for track_name in self.audio_loader.tracks:
            info = self.audio_loader.get_stream_info(track_name)

            render_subtitled_track_video(
                srt_path=os.path.join(self.out_folders[component], f"{track_name}.srt"),
                audio_path=info["source_path"],
                output_path=os.path.join(self.viz_folders[component], f"{track_name}.mp4"),
                fps=self.data.fps,
                default_start_frame=self.data.video_start_frame_index,
                video_recipe=video_recipe,
                camera=info.get("camera"),
                fallback_camera=self.detector_config.fallback_camera,
            )
